### ISSUE TITLE
Use WebLAF

### ISSUE THREAD

**Issue by Endogen** [westoncb/HNDesktop#14]
I kind of don't like the hackernews website design so i really could need a desktop client but HNDesktop ist really beautiful ;)
Maybe you could use a LAF that looks a bit nicer? A really good one is WebLAF: https://github.com/mgarin/weblaf

**Comment by westoncb** [comment]
Hey Endogen, unfortunately, I think HNDesktop would require a good bit of work in order for it to be a good alternative, even beyond the look and feel. I was curious how it would look with WebLAF though (thanks for pointing it out—hand't heard of it). It does look and perform better! But it seems to break a couple minor things also (e.g. it has no 'file' icon which I grab from the L&F if I can't get a favicon from the website). Anyway, if you'd like you can try switching to the branch `weblaf` and pull the latest.

![weblaf-screen](https://user-images.githubusercontent.com/3360318/31322227-c155fd94-ac48-11e7-90e2-f3b8419f5599.png)
